### ISSUE TITLE
Finish Village component as per links Carmelite provided

### ISSUE THREAD

**Issue by alisamhh** [nikau-2018/the-va#105]
Once done, create separate ticket for Village styling

**Comment by bryceknz** [comment]
*"I Say My Name With A Mouth Full of Dirt"*
https://soundcloud.com/jahrarager/a-first-reading-i-say-my-name-with-a-mouth-full-of-dirt

*THE LEGEND OF TELESA*
http://www.thecoconet.tv/know-your-roots/pacific-history-legends/the-legend-of-telesa/

*'I longa ha taha - Indira Moala*
https://www.youtube.com/watchv=RcEA1b5veLM&index=1&list=PLSaTQhnuF5X140w__7yPZHlIVIDtKYfcu

*I THOUGHT I RECOGNISED HER - JOSIE ÈDAN OLOITO'A*
https://www.goodrally.com/blog/2017/6/12/i-thought-i-recognised-her-josie-edan-oloitoa

**Comment by emmanio** [comment]
![village](https://user-images.githubusercontent.com/39945540/45983142-9831a400-c0af-11e8-8a0e-ea2a44a1ab08.jpeg)
